# Generated by Django 5.2.3 on 2025-06-13 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('name', models.CharField(db_column='tx_contato', max_length=70)),
                ('age', models.IntegerField(db_column='nb_idade')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('dominio', models.CharField(db_column='tx_dominio', max_length=70)),
                ('email', models.EmailField(db_column='tx_email', max_length=254)),
                ('contato', models.ForeignKey(db_column='tx_contato', on_delete=django.db.models.deletion.CASCADE, to='Agenda.contato')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('codigo_telefone', models.CharField(db_column='tx_codigo_telefone', max_length=2)),
                ('NumeroTelefone', models.IntegerField(db_column='tx_numero_telefone', max_length=11)),
                ('Contato', models.ForeignKey(db_column='tx_contato', on_delete=django.db.models.deletion.CASCADE, to='Agenda.contato')),
                ('email', models.ForeignKey(db_column='tx_email', on_delete=django.db.models.deletion.CASCADE, to='Agenda.email')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('active', models.BooleanField(db_column='cs_active', default=True)),
                ('Parentesco', models.IntegerField(db_column='tx_parentesco', max_length=16)),
                ('Contato', models.ForeignKey(db_column='tx_contato', on_delete=django.db.models.deletion.CASCADE, to='Agenda.contato')),
                ('Email', models.ForeignKey(db_column='tx_email', on_delete=django.db.models.deletion.CASCADE, to='Agenda.email')),
                ('Telefone', models.ForeignKey(db_column='tx_telefone', on_delete=django.db.models.deletion.CASCADE, to='Agenda.telefone')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
    ]
