# Generated by Django 5.2.3 on 2025-06-14 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefone',
            name='Contato',
        ),
        migrations.AlterField(
            model_name='emergencia',
            name='Parentesco',
            field=models.CharField(db_column='tx_parentesco', max_length=16),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='NumeroTelefone',
            field=models.BigIntegerField(db_column='tx_numero_telefone'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='email',
            field=models.ForeignKey(db_column='tx_email', on_delete=django.db.models.deletion.DO_NOTHING, to='Agenda.email'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='contato',
            field=models.ForeignKey(db_column='tx_contato', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Agenda.contato'),
        ),
    ]
