# Generated by Django 5.2.3 on 2025-06-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_remove_telefone_contato_alter_emergencia_parentesco_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emergencia',
        ),
    ]
